name: Spencer Barton
permalinks: pretty
markdown: redcarpet
highlighter: pygments
safe: true
lsi: false
timezone: America/Los_Angeles
exclude: [Gemfile, Gemfile.lock, README.md, TODO.txt, quotes/index.html, interests/index.html, blog/index.html]
