name: Spencer Barton
permalink: /:year/:month/:day/:title/
highlighter: pygments
safe: true
lsi: false
timezone: America/LA
exclude: [Gemfile, Gemfile.lock, README.md, TODO.txt, sbarton272.github.io.sublime*]
