title: Spencer Barton
permalink: /:year/:month/:day/:title/
highlighter: rouge
safe: true
lsi: false
timezone: America/LA
exclude: [
	Gemfile,
	Gemfile.lock,
	README.md,
	TODO.md
]
plugins:
  - jekyll-sitemap